events/urls.py
from django.conf.urls import patterns, url, include

from events import views

from django.views.decorators.csrf import csrf_exempt

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    #url(r'^filterCity(?P<city>[\w|\W]+)/$', views.index, name='index'),
    #url(r'^filterVenue(?P<venue>[\w|\W]+)/$', views.index, name='index'),
    url(r'^(?P<event_id>\d+)/$', views.detail, name='events'),
    url(r'createanevent/$', views.createanevent, name='createanevent'),
    url(r'delete/(?P<event_id>\d)$', views.deleteticket, name='deleteticket'),


)

hello/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from hello import views

from api import EntryResource
whatever_resource = EntryResource()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(whatever_resource.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^browse/', views.browse, name = "browse"),
    url(r'^addevent/$', views.addevent, name='addevent'),
    url(r'^event/', include('events.urls', namespace = "events")),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^isloggedin/$', views.is_user_logged_in, name='checkLogin'),
    #url(r'^profile/$', views.profile, name='profile'),
    url(r'^about/', views.about, name='about'),
    url(r'^faq/', views.faq, name='faq'),
    url(r'^jobs/', views.jobs, name='jobs'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^terms/', views.terms, name='terms'),
    url(r'^(?P<username>\w+)/$', views.profile, name='profile'),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'start$', views.start, name="start"),
    url(r'ajax-upload$', views.import_uploader, name="my_ajax_upload"),
    url(r'^summernote/', include('django_summernote.urls')),
)

events/forms.py
from datetime import date, datetime
from calendar import monthrange
 
from django import forms
 
from events.models import Sale
 
class CreditCardField(forms.IntegerField):
    def clean(self, value):
        """Check if given CC number is valid and one of the
           card types we accept"""
        if value and (len(value) < 13 or len(value) > 16):
            raise forms.ValidationError("Please enter in a valid "+\
                "credit card number.")
        return super(CreditCardField, self).clean(value)
 
class CCExpWidget(forms.MultiWidget):
    """ Widget containing two select boxes for selecting the month and year"""
    def decompress(self, value):
        return [value.month, value.year] if value else [None, None]
 
    def format_output(self, rendered_widgets):
        html = u' / '.join(rendered_widgets)
        return u'<span style="white-space: nowrap;">%s</span>' % html
 
class CCExpField(forms.MultiValueField):
    EXP_MONTH = [(x, x) for x in xrange(1, 13)]
    EXP_YEAR = [(x, x) for x in xrange(date.today().year,
                                       date.today().year + 15)]
    default_error_messages = {
        'invalid_month': u'Enter a valid month.',
        'invalid_year': u'Enter a valid year.',
    }
 
    def __init__(self, *args, **kwargs):
        errors = self.default_error_messages.copy()
        if 'error_messages' in kwargs:
            errors.update(kwargs['error_messages'])
        fields = (
            forms.ChoiceField(choices=self.EXP_MONTH,
                error_messages={'invalid': errors['invalid_month']}),
            forms.ChoiceField(choices=self.EXP_YEAR,
                error_messages={'invalid': errors['invalid_year']}),
        )
        super(CCExpField, self).__init__(fields, *args, **kwargs)
        self.widget = CCExpWidget(widgets =
            [fields[0].widget, fields[1].widget])
 
    def clean(self, value):
        exp = super(CCExpField, self).clean(value)
        if date.today() > exp:
            raise forms.ValidationError(
            "The expiration date you entered is in the past.")
        return exp
 
    def compress(self, data_list):
        if data_list:
            if data_list[1] in forms.fields.EMPTY_VALUES:
                error = self.error_messages['invalid_year']
                raise forms.ValidationError(error)
            if data_list[0] in forms.fields.EMPTY_VALUES:
                error = self.error_messages['invalid_month']
                raise forms.ValidationError(error)
            year = int(data_list[1])
            month = int(data_list[0])
            # find last day of the month
            day = monthrange(year, month)[1]
            return date(year, month, day)
        return None
 
class SalePaymentForm(forms.Form):
    
    def __init__(self,*args,**kwargs):
        self.menu_opt = kwargs.pop('menu')
        super(SalePaymentForm,self).__init__(*args,**kwargs)
        self.fields['price'] = forms.ChoiceField(widget = forms.Select(), choices = (self.menu_opt), initial=1, required = True)
    
    number = CreditCardField(required=True, label="Card Number")
    name = forms.CharField(required=True, label="Name")
    expiration = CCExpField(required=True, label="Expiration")
    cvc = forms.IntegerField(required=True, label="CCV Number",
        max_value=999, widget=forms.TextInput(attrs={'size': '3'}))
    #price = forms.ChoiceField(widget = forms.Select(), 
     #   choices = (self.menu_opt), initial=1, required = True) #[(1000,'Tier 1',t), (2000,'Tier 2'),(3000,'Tier 3'), ]
    uri = forms.CharField(widget=forms.HiddenInput(),required= True)

#    def clean(self):
#        """
#        The clean method will effectively charge the card and create a new
#        Sale instance. If it fails, it simply raises the error given from
#        Stripe's library as a standard ValidationError for proper feedback.
#        """
#        cleaned = super(SalePaymentForm, self).clean()
 
#        if not self.errors:
#            number = self.cleaned_data["number"]
#            name = self.cleaned_data["name"]
#            exp_month = self.cleaned_data["expiration"].month
#            exp_year = self.cleaned_data["expiration"].year
#            cvc = self.cleaned_data["cvc"]
#            price = self.cleaned_data["price"]
#            uri  = self.cleaned_data['uri']
 
#            sale = Sale()
# 
#            # let's charge $10.00 for this particular item
#            success, instance = sale.charge(price, number, name, exp_month,
#                                                exp_year, cvc)
# 
#            if not success:
#                raise forms.ValidationError("Error: %s" % instance.message)
#            else:
#                instance.save()
#                # we were successful! do whatever you will here...
#                # perhaps you'd like to send an email...
#                pass
#        return cleaned

events/views.py
#from hgext.inotify.linux.watcher import event
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.http import Http404
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.core.exceptions import ObjectDoesNotExist
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from django.forms.models import modelformset_factory
#from django.contrib.gis.geoip import GeoIP
from django.core.mail import EmailMessage

from events.models import Event, Sale, EventViews
from events.forms import SalePaymentForm
from events.models import Event, Ticket, SingletonSiteParams

from hello.forms import EventForm


from tasks import process_event
import json
from allauth.account.forms import LoginForm, SignupForm


#@login_required
#@csrf_protect
def detail(request, event_id):
    try:
        c = {}
        d = []
        event = Event.objects.get(pk=event_id)
        event_tier1 = event.tier_one_tickets
        event_tier2 = event.tier_two_tickets
        event_tier3 = event.tier_three_tickets
        
        ticket = Ticket.objects.filter(event_id_id=event_id)
        ticket_user = Ticket.objects.filter(holder_id=request.user.id, event_id_id = event_id)
        if ticket_user:
            c['exists'] = 'true'

        if event_tier1:
            ticket_tier1 = ticket.filter(event_tier =1).count()
            if int(ticket_tier1) >= int(event_tier1):
                c['tier_one'] = 'No tickets available'
                c['one.error'] = True
            else:
                c['tier_one'] = int(event_tier1)-int(ticket_tier1)
                d.append((1000,'Tier 1'))
            
        if event_tier2:
            ticket_tier2 = ticket.filter(event_tier =2).count()
            if int(ticket_tier2) >= int(event_tier2):
                c['tier_two'] = 'No tickets available'
            else:
                c['tier_two'] = int(event_tier2)-int(ticket_tier2)
                d.append((2000,'Tier 2'))
            
        if event_tier3:
            ticket_tier3 = ticket.filter(event_tier =3).count()
            if int(ticket_tier3) >= int(event_tier3):
                c['tier_three'] = 'No tickets available'
            else:
                c['tier_three'] = int(event_tier3)-int(ticket_tier3)
                d.append((3000,'Tier 3'))
            
    except Event.DoesNotExist:
        raise Http404
    if request.method == "POST":
        form_tier1 = SalePaymentForm(request.POST,menu=d)    
        
        if form_tier1.is_valid(): # charges the card
            
#        ticket_form_set = modelformset_factory(Ticket, fields =('event_id', 'event_tier',
#                                        'balanced_uri', 'card_name', 'card_four_digits'))
#        ticket_form = ticket_form_set(request.POST)
#        if ticket_form.is_valid():
            tier_num = '0'
            if form_tier1.cleaned_data['price'] == '1000' :tier_num = '1'
            if form_tier1.cleaned_data['price'] == '2000' :tier_num = '2'
            if form_tier1.cleaned_data['price'] == '3000' :tier_num = '3' 
            ticket = Ticket(holder = request.user,
                            event_id = event,
                            event_tier = tier_num,
                            balanced_uri = form_tier1.cleaned_data['uri'],
                            card_name = form_tier1.cleaned_data['name'],
                            card_four_digits = str(form_tier1.cleaned_data['number'])[:4],
                            )
            ticket.save()


            event.update_funding_status()

            if event.funding_status == 100 and not event.is_tipped:
                process_event.delay(event)
                
                #pass
                
                

            # email user: thank you for your support
            if request.user.email:
                message ='Dear '+ request.user.username +',\n'+'Thanks a ton for your support towards the event "'+ event.evname +'".\n'+'Have an awesome time there. You deserve it.\n Your credit card will not be charged until the event has tipped. \n -Revel Raise'
                email = EmailMessage('Event Ticket - '+ event.evname, message, to=[request.user.email])
                email.send()
#            request.user.email_user('Ravel Raise Ticket purchase:Thank you',message)

            if event.is_tipped:
                ticket.charge()
                if request.user.email:
                    message ='Dear '+ request.user.username +',\n The' + event.evname + 'event you signed up for is now Tipped.\
                     Which means The event is on!!! Your credit card will be charged shortly.\n Hope you have an awesome time there.\n -Revel Raise.'
                    email = EmailMessage('Event Ticket - '+ event.evname, message, to=[request.user.email])
                    email.send()
    #                request.user.email_user('Ravel Raise Ticket purchase:Thank you',message)

            user = request.user
            redir = '/%s/?w=true' % user
            data = [{'redir': redir}]
            return HttpResponse(json.dumps(data))
            #return redirect('/accounts/%s/?w=true' % user)
    else:
        form_tier1 = SalePaymentForm(menu=d)
        if request.user.is_authenticated() and Ticket.objects.filter(holder_id=request.user, status ='U',event_id_id=event_id):
            c['ticket_remove'] = True
        #page-view counter
        try:
            EventView = EventViews.objects.get(event_id_id=event_id)
            EventViews.objects.filter(event_id_id=event_id).update(count= F("count") + 1)
        except ObjectDoesNotExist:  
            EventView = EventViews()      
            EventView.event_id = event
            EventView.count = 1
            EventView.save()
        names_list = {}
        money_raised = ''
        tier_tally = {}

        if request.user.is_authenticated() and request.user == event.creator:
            sum = 0
            tier_tally['tier_1'] = 0
            tier_tally['tier_2'] = 0
            tier_tally['tier_3'] = 0
            
            for each in Ticket.objects.filter(event_id_id=event_id):
                names_list[each.holder.first_name + " " + each.holder.last_name] = each.event_tier
                sum = sum + float(event.get_tier_price(each.event_tier))
                if each.event_tier == "1":
                    tier_tally['tier_1'] = tier_tally['tier_1'] + 1
                elif each.event_tier == "2":
                    tier_tally['tier_2'] = tier_tally['tier_2'] + 1
                elif each.event_tier == "3":
                    tier_tally['tier_3'] = tier_tally['tier_3'] + 1
                    
            money_raised = sum
            
    return render_to_response("events/detail.html",c,
                    RequestContext( request, {'form': form_tier1, 'event':event, 
                                              'names':names_list, 'money':money_raised, 'tier_tally':tier_tally}) )


def createanevent(request):
    logged_user = request.user
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)

        if form.is_valid():
            # If form has passed all validation checks then continue to save member.
            tier_one = add_gateway_comission(form.cleaned_data['tier_one']) 
            tier_one_post_tipp = add_gateway_comission(form.cleaned_data['tier_one_post_tipp'])
            
            tier_two = add_gateway_comission(form.cleaned_data['tier_two'])
            tier_two_post_tipp = add_gateway_comission(form.cleaned_data['tier_two_post_tipp'])
            
            tier_three = add_gateway_comission(form.cleaned_data['tier_three']) 
            tier_three_post_tipp = add_gateway_comission(form.cleaned_data['tier_three_post_tipp'])
            
            try:
                event = Event(creator=request.user, 
                              evname=form.cleaned_data['evname'], 
                              descr=form.cleaned_data['descr'],
                               
                              tier_one = str(tier_one), 
                              tier_one_desc = form.cleaned_data['tier_one_desc'],
                              tier_one_tickets = form.cleaned_data['tier_one_tickets'], 
                              tier_one_post_tipp = str(tier_one_post_tipp),
                              
                              tier_two = str(tier_two), 
                              tier_two_desc = form.cleaned_data['tier_two_desc'],
                              tier_two_tickets = form.cleaned_data['tier_two_tickets'], 
                              tier_two_post_tipp = str(tier_two_post_tipp),
                              
                              tier_three = str(tier_three),  
                              tier_three_desc=form.cleaned_data['tier_three_desc'],
                              tier_three_tickets = form.cleaned_data['tier_three_tickets'], 
                              tier_three_post_tipp = str(tier_three_post_tipp), 
                              
                              location=form.cleaned_data['location'], 
                              address=form.cleaned_data['address'], 
                              phone=form.cleaned_data['phone'], 
                              website=form.cleaned_data['website'], 
                              pic=form.cleaned_data['pic'], 
                              vid_embed=form.cleaned_data['vid_embed'],
                              tipp_point = str(add_rr_comission(form.cleaned_data['tipp_point'])),
                              last_date = form.cleaned_data['last_date'])
                event.save()
            except:
                return HttpResponse("error")
            # Save is done redirect member to logged in page.

events/templates/events/detail.html
{% extends 'base/base.html' %}



		<title>{% block title %}Events{% endblock %}</title>

 		{% block extrahead %}
		<link rel="stylesheet" href="{{STATIC_URL}}css/detail.css" type="text/css">
		<link rel="stylesheet" href="{{STATIC_URL}}css/stripe.css" type="text/css">
		<script type="text/javascript" src="https://js.balancedpayments.com/v1/balanced.js"></script>
		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
		<script src="{{STATIC_URL}}js/googlemaps.js"></script>

	<script>
		$(document).ready(function () {
			balanced.init('/v1/marketplaces/TEST-MP3BUTNlzLlEQq7B5TB5fpq0')
			$('.ticket-delete').click(function(){
				window.location.reload(true)
			})
			$("#purchase-form").submit(function(event){
				event.preventDefault()
				var payload = {
			        card_number: $('#id_number').val(),
			        expiration_month: $('#id_expiration_0').val(),
			        expiration_year: $('#id_expiration_1').val(),
			        security_code: $('#id_cvc').val()
			    };
			    balanced.card.create(payload, function (response) {
			        // Successful tokenization
			        if(response.status === 201 && response.data) {
			            // Send to your backend
			            $("#id_uri").val(response.data.uri);
			            // $('form#purchase-form').submit();
			             jQuery.post('', $('form#purchase-form').serialize()
			             //{
			                // uri: response.data.uri,
			                // name: $("#id_name").val(),
			                // price: $("#id_price").val(),
			                // 'csrfmiddlewaretoken':'{{csrf_token}}'
			            // }, 
			            , function(r) {
			                // Check your backend response
			                window.location = $.parseJSON(r)[0].redir;
			            });
			        } else {
			            alert('failed to tokenize:\n' + JSON.stringify(response, false, 4))
			        }
			        
			        // Debuging, just displays the tokenization result in a pretty div
			        // $('#response .panel-body pre').html(JSON.stringify(response, false, 4));
			        // $('#response').slideDown(300);
			    })
			})
		})
		$(function() {
		
			$("#nav").addClass("transparent")
		
		
		    $('.ticket-pay').click(function(){ 
		    	// no ajax calls required here.. we just check in the template and send a flag.
			    var loggedin = 0;
			    {% if user.is_authenticated %}
			    loggedin = 1;
			    {% endif %}
			    if(loggedin){
			      $(".overlay").addClass("active").show()
			      tier = $(this).attr("data-id")
			      $("#purchase-form select[name='price']").val(tier);
			    }else{
			    	//this is the part where the pop displays that the user is to loggin to buy the ticket.
			    }
		    });
		    $('.cover').click(function(){
		      $(".overlay").removeClass("active").fadeOut('fast')
		    });
		
			percentt = 1;
			percent = 0;
			event_funding_status = {{event.funding_status}}
			setTimeout(function() {
				percentint = setInterval(function() {
					$(".event-percent").html(Math.floor(percent)+"%")
					percent = Math.pow(percentt, 0.9)
					percentt++
					if (percent > event_funding_status+1) {
						clearInterval(percentint)
					}
				}, 10)
			}, 1000)
		
			tally_1 = {{tier_tally.tier_1}}
			tally_total = tally_1 
			$(".tickets-sold").html(tally_total)
			tier_1_rev = tally_1 * {{event.tier_one}};
			$(".tier-one-stat .sub-stat-rev span").html(tier_1_rev)
		})
	</script>


	{% endblock %}
	{% block content %}
	<div class="event-pic">
		<img src="{{STATIC_URL}}/{{event.pic}}" alt="">
	</div>
	<div class="event-main">
		<div class="event-bottom-container">
			{% if user.is_authenticated and user.id == event.creator_id %}
			<div class="admin-panel">
				<div class="left-admin">
					<div class="admin-c">
						{% if names %}
						<div class="admin-title guest-list-title">Guest List</div>
						<div class="guestlist">
							{% for key, values in names.items %}
						        <div class="guest">{{key}}<span>Tier {{values}}</span></div>
						     {% endfor %}
						</div>
						{% endif %}							
					</div>
					<div class="admin-c">
						<div class="admin-title event-stats-title">Event Stats</div>
						<div class="stat-list">
							<div class="stat-title">Tickets Sold (<span class="tickets-sold">0</span>)</div>
								<div class="sub-stat-c">
									<div class="sub-stat tier-one-stat">
										<div class="sub-stat-title">Tier 1</div>
										<div class="sub-stat-val sub-stat-qty">{% if tier_tally.tier_1 %}{{tier_tally.tier_1}}{% else %}0{% endif %}</div>
										<div class="sub-stat-val sub-stat-rev">$<span>0</span></div>
									</div>
									{% if event.tier_two %}
									<div class="sub-stat tier-two-stat">
										<div class="sub-stat-title">Tier 2</div>
										<div class="sub-stat-val sub-stat-qty">{% if tier_tally.tier_2 %}{{tier_tally.tier_2}}{% else %}0{% endif %}</div>
										<div class="sub-stat-val sub-stat-rev">$<span>0</span></div>
									</div>
									{% endif %}
									{% if event.tier_three %}
									<div class="sub-stat tier-three-stat">
										<div class="sub-stat-title">Tier 3</div>
										<div class="sub-stat-val sub-stat-qty">{% if tier_tally.tier_3 %}{{tier_tally.tier_3}}{% else %}0{% endif %}</div>
										<div class="sub-stat-val sub-stat-rev">$<span>0</span></div>
									</div>
									{% endif %}
								</div>
							<div class="stat-title">Money Raised<span class="stat-val">${% if money %}{{money}}{% else %}0{% endif %}</span></div>
							<div class="stat-title">Goal<span class="stat-val">{{event.tipp_point}}</span></div>
						</div>	
					</div>
			
				</div>
				<div class="right-admin">
					<div class="admin-button admin-share"><span>Share</span></div>
					<div class="admin-button admin-funds"><span>Receive Funds</span></div>
					<div class="admin-button"><div class="ab-title">Admin Panel</div></div>
					<div class="admin-button admin-edit"><span>Edit Details</span></div>
				</div>
			</div>	
			{% endif %}				
			<div class="event-main-wrap">
				<div class="event-name">
					<span>{{ event.evname }}</span>
				</div>
				<div class="event-main-right">
					<div class="event-percent">0%</div>
					<div class="event-main-location">{{ event.address }}</div>
				</div>
				<div class="event-bottom">
					<div class="event-video">{{ event.vid_embed|safe }}</div>		
					<div class="event-tiers">
						<div class="event-tier">
                            {% if exists %}
                            <a  class="ticket-pay ticket-pay_remove" href="/event/delete/{{ event.id }}" >
                            {% else %}
                            <a class="ticket-pay"data-id="1">
                            {% endif %}
								<div class="tier-price">
									<span>$
	                                    {% if event.is_tipped %}
	                                    {{ event.tier_one_post_tipp }}
	                                    {% else %}
	                                    {{ event.tier_one }}
	                                    {% endif %}
	                                </span>
								</div>
								<div class="tier-description">
									<span>{{ event.tier_one_desc }}</span>
									<span class="qty">Available Tickets:{{tier_one}}</span>	
								</div>
								{% if exists %}
                                <div class="purchase-logo">-</div>
                                {% else %}
                                 <div class="purchase-logo">+</div>
                                {% endif %}
							</a>
						</div>
						{% if event.tier_two %}
						<div class="event-tier">
							{% if exists %}
                            <a  class="ticket-pay_remove" href="/event/delete/{{ event.id }}" >
                            {% else %}
                            <a class="ticket-pay"data-id="1">
                            {% endif %}
								<div class="tier-price">
									<span>$
		                                {% if event.is_tipped %}
		                                {{ event.tier_two_post_tipp }}
		                                {% else %}
		                                {{ event.tier_two }}
		                                {% endif %}
		                            </span>
								</div>
								<div class="tier-description">
									<span>{{ event.tier_two_desc }}</span>
									<span class="qty">Available Tickets:{{tier_two}}</span>
								</div>
								{% if exists %}
                                <div class="purchase-logo">-</div>
                                {% else %}
                                 <div class="purchase-logo">+</div>
                                {% endif %}
							</a>
						</div>
						{% endif %}
						{% if event.tier_three %}
						<div class="event-tier">
							{% if exists %}
                            <a  class="ticket-pay_remove" href="/event/delete/{{ event.id }}" >
                            {% else %}
                            <a class="ticket-pay"data-id="1">
                            {% endif %}
								<div class="tier-price">
									<span>$
		                                {% if event.is_tipped %}
		                                {{ event.tier_three_post_tipp }}
		                                {% else %}
		                                {{ event.tier_three }}
		                                {% endif %}
		                            </span>
								</div>
								<div class="tier-description">
									<span>{{ event.tier_three_desc }}</span>
									<span class="qty">Available Tickets:{{tier_three}}</span>
								</div>
								{% if exists %}
                                <div class="purchase-logo" >-</div>
                                {% else %}
                                <div class="purchase-logo">+</div>
                                {% endif %}
							</a>
						</div>
						{% endif %}					
					</div>
				</div>
			</div>
			<div class="event-left">
				<div class="event-description"><span>{{ event.descr|safe }}</span></div>
				<div class="location-info">
				    <div id="map-canvas"></div>
					<div class="location-name"><span>{{ event.location }}<span></div>
					<div class="location-address"><span>{{ event.address }}</span></div>
					<div class="location-city"></div>
					<div class="location-map"></div>
					<div class="location-phone"><span>{{ event.phone }}<span></div>
					<div class="location-website"><span>{{ event.website }}</span></div>
				</div>
			</div>	
			<div class="app">
				<div class="overlay">
					<div class="cover"></div>
					<div class="yield">
						<div class="panel" style="margin-top: -248.4px;">
							<header>
								<section class="custom">
									<div class="info">
										<h1>{{event.evname}}</h1>
										<h2>{{event.location}}</h2>
									</div>
								</section>
								<nav>
									<a class="close">Close</a>
								</nav>
							</header>
							<form id="purchase-form" action="" method="post">
								{% csrf_token %}
								{% for field in form %}
								<div class="field-wrapper">
									<div class="field-label">
										{{ field.label_tag }}:
									</div>
									<div class="field-field">
										{{ field }}
										{{ field.errors }}
									</div>
								</div>
								{% endfor %}
								<input type="submit" value="Checkout" />
							</form>
							<div class="success">
								<div class="check"></div>
							</div>
						</div>
					</div>
					<footer class="overlay-footer">
					  <a href="https://stripe.com" target="_blank"><span class="stripe">Powered by Stripe</span></a>
					  <span class="secure">Secure Connection</span>
					</footer>
				</div>
			</div>		
		</div>
	</div>
	{% endblock %}