events/urls.py
from django.conf.urls import patterns, url, include

from events import views

from django.views.decorators.csrf import csrf_exempt

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    #url(r'^filterCity(?P<city>[\w|\W]+)/$', views.index, name='index'),
    #url(r'^filterVenue(?P<venue>[\w|\W]+)/$', views.index, name='index'),
    url(r'^(?P<event_id>\d+)/$', views.detail, name='events'),
    url(r'createanevent/$', views.createanevent, name='createanevent'),
    url(r'delete/(?P<event_id>\d)$', views.deleteticket, name='deleteticket'),


)

hello/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from hello import views

from api import EntryResource
whatever_resource = EntryResource()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(whatever_resource.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^browse/', views.browse, name = "browse"),
    url(r'^addevent/$', views.addevent, name='addevent'),
    url(r'^event/', include('events.urls', namespace = "events")),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^isloggedin/$', views.is_user_logged_in, name='checkLogin'),
    #url(r'^profile/$', views.profile, name='profile'),
    url(r'^about/', views.about, name='about'),
    url(r'^faq/', views.faq, name='faq'),
    url(r'^jobs/', views.jobs, name='jobs'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^terms/', views.terms, name='terms'),
    url(r'^(?P<username>\w+)/$', views.profile, name='profile'),
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'start$', views.start, name="start"),
    url(r'ajax-upload$', views.import_uploader, name="my_ajax_upload"),
    url(r'^summernote/', include('django_summernote.urls')),
)

events/models.py
from django.db import models
from django import forms
import datetime
import json
from django.conf import settings
import datetime
import requests

# Create your models here.

from django.contrib.auth.models import User
from django.forms import ModelForm
from time import time
from django.core.validators import MaxLengthValidator
from django.template.defaultfilters import default
from django.forms.extras.widgets import SelectDateWidget
from singleton_models.models import SingletonModel

class SiteSettings(models.Model):
    gateway_comission = models.FloatField(default = 2.6)
    ravel_raise_comission = models.FloatField(default = 8)


def get_upload_file_name(instance, filename):
    return "uploads/%s_%s" % (str(time()).replace('.','_'), filename)




class Event(models.Model):
    STATUS = (
              ('S', 'Submitted'),
              ('A', 'Accepted'),
              ('R', 'Rejected'),
              ('T', 'Tipped'),
              ('F', 'Finished')
              )
    creator = models.ForeignKey(User)
    evname = models.CharField(("evname"),max_length=60)
    descr = models.TextField(("descr"),max_length=500)
    
    tier_one = models.CharField(("tier_one"),max_length=6, blank=True, null=True)
    tier_one_post_tipp = models.CharField(("tier_one_post_tipp"),max_length=6, blank=True, null=True)
    tier_one_desc = models.CharField(("tier_one_desc"),max_length=140, blank=True, null= True)
    tier_one_tickets = models.CharField(("tier_one_tickets"),max_length=3, blank=True, null= True)
    
    tier_two = models.CharField(("tier_two"),max_length=6, blank=True, null=True)
    tier_two_post_tipp = models.CharField(("tier_two_post_tipp"),max_length=6, blank=True, null=True)
    tier_two_desc = models.CharField(("tier_two_desc"),max_length=140, blank=True, null= True)
    tier_two_tickets = models.CharField(("tier_two_tickets"),max_length=3, blank=True, null= True)
    
    tier_three = models.CharField(("tier_three"),max_length=6, blank=True, null=True)
    tier_three_post_tipp = models.CharField(("tier_three_post_tipp"),max_length=6, blank=True, null=True)
    tier_three_desc = models.CharField(("tier_three_desc"),max_length=140, blank=True, null= True)
    tier_three_tickets = models.CharField(("tier_three_tickets"),max_length=3, blank=True, null= True)
    
#    tierOne = models.ForeignKey(Tier,related_name='tier_one')
#    tierTwo = models.ForeignKey(Tier,related_name='tier_two', null = True)
#    tierThree = models.ForeignKey(Tier,related_name='tier_three', null = True)
    
    location = models.CharField(("location"),max_length=100, null= True)
    address = models.CharField(("address"),max_length=100)
    phone = models.CharField(("phone"),max_length=30, blank=True, null= True)
    website = models.CharField(("website"),max_length=100, blank=True, null= True)
    pic = models.FileField(upload_to=get_upload_file_name)
    vid_embed = models.CharField(("website"),max_length=1000)
    
    tipp_point = models.CharField(("tipp_point"),max_length=10)
    last_date = models.DateField(('last_date'))
    status = models.CharField(max_length = 1, choices=STATUS, default = 'S')
    funding_status = models.IntegerField(("status_percent"), default = 0)
    is_tipped = models.BooleanField(default = False)
    
    #@classmethod
    def update_funding_status(self):
        if self.is_tipped:
            self.funding_status = 100
            self.save() 
            return 100
        sum = 0
        for ticket in Ticket.objects.filter(event_id = self):
            sum = sum + float(self.get_tier_price(ticket.event_tier))
        self.funding_status = int(sum*100/float(self.tipp_point))
        if self.funding_status > 100 : self.funding_status = 100
        self.save() 
        
    
    #@classmethod
    def get_tier_price(self, tier_num):
        if tier_num == '1':
            return self.tier_one_post_tipp if self.is_tipped and\
                       self.tier_one_post_tipp else self.tier_one
        elif tier_num =='2' and self.tier_two:
            return self.tier_two_post_tipp if self.is_tipped and\
                       self.tier_two_post_tipp else self.tier_two
        elif self.tier_three:
            return self.tier_three_post_tipp if self.is_tipped and\
                       self.tier_three_post_tipp else self.tier_three
        return self.tier_one
    
    # On Python 3: def __str__(self):
    def __unicode__(self):
        return self.evname


#class Tier(models.Model):
#    tier_price = models.CharField(("tier_price"),max_length=6, blank=True, null=True)
#    tier_price_post_tipp = models.CharField(("tier_price_post_tipp"),max_length=6, blank=True, null=True)
#    tier_desc = models.CharField(("tier_desc"),max_length=140)
#    event = models.ForeignKey(Event)
#    
#    @classmethod
#    def get_price(self):
#        return self.tier_price_post_tipp if self.event.is_tipped else self.tier_price
#    
#    def __unicode__(self):
#        return self.tier_desc    

class EventViews( models.Model ):
    event_id = models.ForeignKey('events.Event', related_name='views')
    count = models.IntegerField(default=0)

    def __unicode__(self):
        return self.count



class Ticket(models.Model):
    STATUS = (
              ('U', 'Uncharged'),
              ('C', 'Charged'),
              ('D', 'Declined')
              )
    holder = models.ForeignKey(User)
    event_id = models.ForeignKey(Event)
    event_tier = models.CharField(("tier_id"),max_length=1)
    balanced_uri = models.CharField(("balanced_uri"),max_length=100)
    card_name = models.CharField(("card_name"),max_length=20)
    card_four_digits = models.CharField(("card_digits"),max_length=4)
    status = models.CharField(max_length = 1, choices=STATUS, default = 'U')
    
    #@classmethod
    def charge(self):
        if self.status != 'U': return
        base_uri = settings.BALANCED_URL
        customer_uri = base_uri+'/v1/customers'
        usr = settings.BALANCED_KEY #'ak-test-2DBryLFR3BBam1CipbWEGSO6gqVOBKghP'
        
        #add a customer 
#        request = urllib2.Request(customer_uri, data = '')
#        response = urllib2.urlopen(request)
#        res_data = json.load(response)
        
        r = requests.post(customer_uri, auth=(usr, ''))
        res_data = r.json()
        
        res_data['uri'] = '/v1/customers/'+res_data['id']
        
        # add a cc token to the customer
        test_card = '/v1/marketplaces/'+settings.BALANCED_MARKET+'/cards/CC3czjpElvHSwwPt276lUk5i'
        values = {'card_uri':self.balanced_uri}
        r = requests.put(base_uri + res_data['uri'], data = values, auth=(usr, ''))
        res_data = r.json()
        if 'status' in res_data.keys():
            pass # something's wrong .. deal with it.
        
        # and finally charge the customer. 
        values = {"appears_on_statement_as":settings.BALANCED_STATEMENT_TEXT,
                  "amount": 50,  #self.event_id.get_tier_price(self.event_tier),
                  "description":"Revel Raise: Ticket for event "+ self.event_id.evname}
        
        res_data['debits_uri'] = '/v1/customers/'+res_data['id']+'/debits'
        
        r = requests.post(base_uri + res_data['debits_uri'], data = values, auth=(usr, ''))
        res_data = r.json()
        if res_data['status'] != 'succeeded':
            self.status = 'D'
            pass # something's wrong .. deal with it.
        else:
            self.status = 'C'
            sale = Sale()
            res_data['transaction_number']
        self.save()

    # On Python 3: def __str__(self):
    def __unicode__(self):
        return str(self.holder) + str(self.event_id) + str(self.event_tier)

    @classmethod
    def create(self, holder, event_id, tier_id, bal_uri, c_four, c_name):
        ticket = self(holder=holder, event_id=event_id, 
                      event_tier=tier_id, balanced_uri = bal_uri,
                      card_name = c_name, card_four_digits = c_four)
        ticket.save()
        return ticket

class Sale(models.Model):
    ticket = models.ForeignKey(Ticket)
    transaction_number = models.CharField(max_length = 15)
    
    def __unicode__(self):
        return self.transaction_number
    
class SiteParams(SingletonModel):
    ravel_raise_comission = models.FloatField()
    payment_gateway_comission = models.FloatField()


class SingletonSiteParams(models.Model):
    ravel_raise_comission = models.FloatField()
    payment_gateway_comission = models.FloatField()

hello/forms.py
from django import forms

class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')

    def save(self, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()


from events.models import Event
        
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from bootstrap3_datetime.widgets import DateTimePicker

class EventForm(forms.ModelForm):
    evname = forms.CharField(required=True,widget=forms.TextInput(
                                        attrs={'placeholder':'',}))
    descr = forms.CharField(required=True,widget=SummernoteWidget())
    tier_one = forms.CharField(required=True,widget=forms.TextInput(
                                        attrs={'placeholder':'$',}))
    tier_one_post_tipp = forms.CharField(required=False,widget=forms.TextInput(
                                        attrs={'placeholder':'$',}))
    tier_one_desc = forms.CharField(required=True,widget=forms.TextInput(
                                        attrs={'placeholder':'Description',}))
    tier_one_tickets = forms.CharField(required=True,widget=forms.TextInput(
                                        attrs={'placeholder':'# of tickets',}))
    tier_two = forms.CharField(required=False,widget=forms.TextInput(
                                        attrs={'placeholder':'$',}))
    tier_two_post_tipp = forms.CharField(required=False,widget=forms.TextInput(
                                        attrs={'placeholder':'$',}))
    tier_two_desc = forms.CharField(required=False,widget=forms.TextInput(
                                        attrs={'placeholder':'Description',}))
    tier_two_tickets = forms.CharField(required=False,widget=forms.TextInput(
                                        attrs={'placeholder':'# of tickets',}))
    tier_three = forms.CharField(required=False,widget=forms.TextInput(
                                        attrs={'placeholder':'$',}))
    tier_three_post_tipp = forms.CharField(required=False,widget=forms.TextInput(
                                        attrs={'placeholder':'$',}))
    tier_three_desc = forms.CharField(required=False,widget=forms.TextInput(
                                        attrs={'placeholder':'Description',}))
    tier_three_tickets = forms.CharField(required=False,widget=forms.TextInput(
                                        attrs={'placeholder':'# of tickets',}))
    location = forms.CharField(required=True,widget=forms.TextInput(
                                        attrs={'placeholder':'',}))
    location_route = forms.CharField(required=True,widget=forms.TextInput(
                                        attrs={'placeholder':'asdf',}))
    phone = forms.CharField(required=False,widget=forms.TextInput(
                                        attrs={'placeholder':'',}))
    website = forms.CharField(required=False, widget=forms.TextInput(
                                        attrs={'placeholder':'',}))
    tipp_point = forms.CharField(required=True, widget=forms.TextInput(
                                        attrs={'placeholder':'$',}))
    #last_date = forms.DateField(required=True, widget=SelectDateWidget(
                            #attrs={'placeholder':'$',}), initial=datetime.date.today())
    last_date = forms.DateField(widget=DateTimePicker(options={"format": "YYYY-MM-DD",
                                       "pickTime": True}))
    vid_embed = forms.CharField(required=False, widget=forms.TextInput(
                                        attrs={'placeholder':'<iframe>/<embed>',}))

    class Meta:
        model = Event

        fields = ('evname', 'descr', 'tier_one', 'tier_one_desc', 'tier_two',\
                   'tier_two_desc', 'tier_three', 'tier_three_desc', 'location',\
                   'address', 'phone', 'website', 'pic', 'vid_embed',\
                   'tier_one_post_tipp', 'tier_two_post_tipp', 'tier_three_post_tipp',\
                   'tipp_point', 'last_date')
        
        def clean_evname(self):
            evname = self.cleaned_data['evname']
            descr = self.cleaned_data['descr']
            #tier_one = self.cleaned_data['tier_one']
            #tier_one_desc = self.cleaned_data['tier_one_desc']
            #tier_two = self.cleaned_data['tier_two']
            #tier_two_desc = self.cleaned_data['tier_two_desc']
            #tier_three = self.cleaned_data['tier_three']
            #tier_three_desc = self.cleaned_data['tier_three_desc']
            location = self.cleaned_data['location']
            address = self.cleaned_data['address']
            phone = self.cleaned_data['phone']
            website = self.cleaned_data['website']
            pic = self.cleaned_data['pic']
            vid_embed = self.cleaned_data['vid_embed']

            try:
                    Event.objects.get(evname=evname)
            except Event.DoesNotExist:
                    return evname, descr, tier_one, tier_one_desc,\
                         tier_two, tier_two_desc, tier_three, tier_three_desc,\
                         location, address, phone, website, tier_one_post_tipp,\
                         tier_two_post_tipp, tier_three_post_tipp, tipp_point, last_date
            raise forms.ValidationError("Event already exists.")

hello/templates/home/addevent.html
{% extends 'base/base.html' %}
	<title>{% block title %}Submit Event - RevelRaise{% endblock %}</title>
	{% block extrahead %}
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap-theme.css">
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
	<script src="{{STATIC_URL}}js/googlemaps.js"></script>
	<link rel="stylesheet" href="{{STATIC_URL}}css/add_event.css" type="text/css">
    <script src="{{ STATIC_URL }}ajaxuploader/js/fileuploader.js" ></script>
    <script src="{{ STATIC_URL }}js/moment.js" ></script>
    <script src="{{ STATIC_URL }}js/datetime.js" ></script>
	<link rel="stylesheet" href="{{STATIC_URL}}ajaxuploader/css/fileuploader.css" type="text/css">
    <script src="{{STATIC_URL}}bootstrap/js/bootstrap.js"></script>
    {{ form.media }}

	<script>
		$(function() {
			
			browseheader = $("#sticky-sidebar")
			browseheader_top = $(browseheader).offset().top
			navheight = $("#nav").outerHeight()
			startfixed = browseheader_top - navheight - 30
			fixedright = ($(window).width() - $("#main-width").width())/2
			$(".fixed").css("right", fixedright+"px")
			$(window).scroll(function() {
				scrolltop = $(document).scrollTop();
				if (scrolltop > startfixed) {
					$(browseheader).addClass("fixed")
					fixedright = ($(window).width() - $("#main-width").width())/2
					$(".fixed").css("right", fixedright+"px")
				}else {
					$(browseheader).removeClass("fixed")
				}
			})
		
			tier = 1;
			$(".add-tier").click(function() {
				$(".remove-tier").show()
				tier++;
				if (tier == 2){
					$(".add-tier").before('<div class="event-tier tier-two"><div class="tier-price editable"><span></span>{{ event_form.tier_two }}</div><div class="tier-description editable"><span></span>{{ event_form.tier_two_desc }}</div><div class="tier-tickets editable"><span></span>{{ event_form.tier_two_tickets }}</div><div class="event-tier-post"><div class="post-tier-price editable"><span></span>{{ event_form.tier_two_post_tipp }}</div></div></div>')
					$("#pc-tier-two").show()
				}
				else if (tier == 3){
					$(".add-tier").before('<div class="event-tier tier-three"><div class="tier-price editable"><span></span>{{ event_form.tier_three }}</div><div class="tier-description editable"><span></span>{{ event_form.tier_three_desc }}</div><div class="tier-tickets editable"><span></span>{{ event_form.tier_three_tickets }}</div><div class="event-tier-post"><div class="post-tier-price editable"><span></span>{{ event_form.tier_three_post_tipp }}</div></div></div>')
					$("#pc-tier-three").show()
					$(".add-tier").hide()
				}
			    if ($('#pricechange').is(":checked")) {
					$(".tier-description").addClass("widthchange")
					$(".event-tier-post").show()
			    }
				update_pc()
			})
		
			$( ".remove-tier").click("click", function() {
				if (tier == 2){
					$(".tier-two").remove()
					$("#pc-tier-two").hide()
					$(".remove-tier").hide()
				}
				else if (tier == 3){
					$(".tier-three").remove()
					$("#pc-tier-three").hide()
					$(".add-tier").show()
				}
				tier--;
				update_pc()
			})
		
		
			$('form').find('input').keypress(function(e){
			    if ( e.which == 13 ) { // Enter key = keycode 13
			        $(this).next().focus();  //Use whatever selector necessary to focus the 'next' input
			    	return false;
			    }
			});
		
			$("label[for='pricechange']").click(function() {
				$(".tier-description").toggleClass("widthchange")
				$(".event-tier-post").toggle()
			})
			
		
			$(document).on("blur","input", update_preview)
			
			function update_preview() {
				$(".article .title").html($("#id_evname").val())
				$(".article .venue").html($("#id_location").val())
				//$(".article .date-time").html($("#id_last_date_month").val())
				$(".article .location").html($("#id_address").val())
			}
		
		
			$(document).on("blur","#id_tipp_point, .tier-price input, .tier-tickets input", update_pc)
		
			function update_pc() {
				tier_two_price = $("#id_tier_two").val()
				tier_two_qty = $("#id_tier_two_tickets").val()
				tier_two_amt = tier_two_price*tier_two_qty;
				if (tier_two_price && tier_two_qty) {
					$("#pc-tier-two .pc-qty-price").html(tier_two_price+"x"+tier_two_qty)
					$("#pc-tier-two .pc-total").html(tier_two_amt)
				}else {
					$("#pc-tier-two .pc-qty-price").html(0+"x"+0)
					$("#pc-tier-two .pc-total").html(0)		
				}
				
				tier_three_price = $("#id_tier_three").val()
				tier_three_qty = $("#id_tier_three_tickets").val()
				tier_three_amt = tier_three_price*tier_three_qty;
				if (tier_three_price && tier_three_qty) {
					$("#pc-tier-three .pc-qty-price").html(tier_three_price+"x"+tier_three_qty)
					$("#pc-tier-three .pc-total").html(tier_three_amt)
				}else {
					$("#pc-tier-three .pc-qty-price").html(0+"x"+0)
					$("#pc-tier-three .pc-total").html(0)		
				}
				
				tier_one_price = $("#id_tier_one").val()
				tier_one_qty = $("#id_tier_one_tickets").val()
				tier_one_amt = tier_one_price*tier_one_qty;
				if (tier_one_price && tier_one_qty) {
					$("#pc-tier-one .pc-qty-price").html(tier_one_price+"x"+tier_one_qty)
					$("#pc-tier-one .pc-total").html(tier_one_amt)
					rev = tier_one_amt+tier_two_amt+tier_three_amt
					$("#pc-rev .pc-val").html(rev)
					fee = rev*0.03;
					$("#pc-fee .pc-val").html(Math.round(fee))
					net = rev - fee;
					$("#pc-diff .pc-val").html(net)
				}else {
					$("#pc-tier-one .pc-qty-price").html(0+"x"+0)
					$("#pc-tier-one .pc-total").html(0)		
				}
				
				tipp_amt = $("#id_tipp_point").val()
				if (tipp_amt)
				$("#pc-tip span").html(tipp_amt)
				else
				$("#pc-tip span").html(0)
			
			}
		
			{% if user.is_authenticated %}
			user_logged_in = true;
			{% else %}
			user_logged_in = false;
			{% endif %}
			if (!user_logged_in) {
					$(".popup-container").css("opacity", 0).show().fadeTo(100, 1)
					$("#signup-form").hide();			
					$("#login-form").show();
				setTimeout(function() {
					$(".popup-container").unbind("click")
				}, 100)
			}
		
		
			var uploader = new qq.FileUploader({
			    action: "{% url 'my_ajax_upload' %}",
			    element: $('#file-uploader')[0],
			    multiple: true,
			    onComplete: function(id, fileName, responseJSON) {
			        if(responseJSON.success) {
			            //console.log("success!");
			            $("#preview .picture img").attr("src", "http://revelraise.com/static/uploads/"+responseJSON.filename)
			        } else {
			            //console.log("upload failed!");
			        }
			    },
			    onAllComplete: function(uploads) {
			        //console.log("All complete!");
			    },
			    params: {
			        'csrf_token': '{{ csrf_token }}',
			        'csrf_name': 'csrfmiddlewaretoken',
			        'csrf_xname': 'X-CSRFToken',
			    },
			});
		})
	</script>
	{% endblock %}
	{% block content %}
		<div class="addevent-content">
			<form action="{% url 'events:createanevent' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
				<div class="form-section-label"></div>
				<div class="event-name editable">
					<div class="form-label">Name</div>
					{{ event_form.evname }}
				</div>
				<div class="location-website editable">
					<div class="form-label">Date and Time</div>
					{{ event_form.last_date }}
				</div>
				<div class="event-pic">
					<div class="form-label">Picture</div>
					{{ event_form.pic }}
				    <div id="file-uploader">       
				        <noscript>          
				            <p>Please enable JavaScript to use file uploader.</p>
				        </noscript>         
				    </div>
				</div>
				<div class="media-edit">
					<div class="edit-pic edit-media-btn"></div>
					<div class="edit-vid-embed edit-media-btn">
						<div class="video-embed-c">
							<div class="form-label">Video Embed</div>
							<div class="embed-input">{{ event_form.vid_embed }}</div>
						</div>
					</div>
				</div>
				<div class="form-section-label">Location</div>
				<div class="location-name editable">
					<div class="form-label">Venue</div>
					{{ event_form.location }}
					{{ event_form.location_route }}
				</div>
				<div class="location-address editable">
					<div class="form-label">Address</div>
					<div class="location-left">
						{{ event_form.address }}
						<div id="googlemaps-output"></div>				
					</div>
					<div id="map-canvas"></div>
				</div>
				<div class="event-tier-c">
					<div class="form-section-label">Tickets</div>
					<div class="tier-options addevent-c">
						<div class="tier-option">
							<input type="checkbox" id="pricechange" name="pricechange" />
							<label for="pricechange">Change price after funding</label>
						</div>
					</div>
					<div class="event-tiers event-tiers-left">
						<div class="event-tier addevent-c">
							<div class="form-label">Tier One</div>
							<div class="tier-price editable">{{ event_form.tier_one }}</div>
							<div class="tier-description editable">{{ event_form.tier_one_desc }}</div>
							<div class="tier-tickets editable">{{ event_form.tier_one_tickets }}</div>
							<div class="event-tier-post">
								<div class="post-tier-price editable">{{ event_form.tier_one_post_tipp }}</div>
							</div>
						</div>
					</div>
					<div class="tier-button add-tier addevent-c">Add a Tier</div>
					<div class="tier-button remove-tier addevent-c">Remove Tier</div>				
				</div>
				<div class="tipp-date-c addevent-c">
					<div class="location-website editable">
						<div class="form-label">Goal</div>
						{{ event_form.tipp_point }}
					</div>				
				</div>
				<div class="event-description editable addevent-c">
					<div class="form-label">Description</div>
					{{ event_form.descr }}
				</div>
				<div class="location-info addevent-c">
					<div class="location-input-c">
						<div class="location-phone editable">
							<div class="form-label">Phone (optional)</div>
							{{ event_form.phone }}
						</div>
						<div class="location-website editable">
							<div class="form-label">Website (optional)</div>
							{{ event_form.website }}
						</div>
					</div>
				</div>
				<div class="publish">
					<input type="submit" value="Submit" />
				</div>
			</form>
			<div id="sticky-sidebar">
				<div id="preview">
					<div class="article">
						<div class="overlay"></div>
						<div class="picture"><img src="" alt=""></div>
						<div class="title"></div>
						<div class="info">
							<div class="venue"></div>
							<div class="date-time">
								<div class="date"></div>
								<div class="time"></div>									
							</div>
						</div>
						<div class="location">{{ event.address }}</div>
					</div>
				</div>
				<div class="price-cost-calc-c">
					<div class="pccc-title">Financials</div>
					<div class="pc-tier-c">
						<div id="pc-tier-one" class="pc-tier-row">
							<div class="pc-tier">Tier 1</div>
							<div class="pc-qty-price">0x0</div>
							<div class="pc-total">0</div>							
						</div>
						<div id="pc-tier-two" class="pc-tier-row" style="display:none">
							<div class="pc-tier">Tier 2</div>
							<div class="pc-qty-price">0x0</div>
							<div class="pc-total">0</div>							
						</div>
						<div id="pc-tier-three" class="pc-tier-row" style="display:none">
							<div class="pc-tier">Tier 3</div>
							<div class="pc-qty-price">0x0</div>
							<div class="pc-total">0</div>							
						</div>
					</div>
					<div id="pc-rev" class="pc-title">Revenue<span class="pc-val">0</span></div>
					<div id="pc-fee" class="pc-title">Service Fee <span>(7%)</span><span class="pc-val">0</span></div>
					<div id="pc-diff" class="pc-title">Net<span class="pc-val">0</span></div>
					<div class="pc-tip-c">
						<div id="pc-tip" class="pc-title">Tip Point<span class="pc-val">0</span></div>
					</div>
				</div>		
			</div>
		</div>
		{% endblock %}

hello/templates/home/loginc.html
<div class="log-in-c">
	{% load i18n %}
	{% load account %}
	{% load url from future %}
	<form class="login" method="POST" action="{% url 'account_login' %}">
	  {% csrf_token %}
	  {{ form.as_p }}
	  {% if redirect_field_value %}
	  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
	  {% endif %}
	  <a class="secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
	  <button class="primaryAction" type="submit">{% trans "Sign In" %}</button>
	</form>
</div>